title: "Pythonvishal - Python for accounting, business and finance"
email: wowthemesnet@gmail.com
timezone: UTC
baseurl: "/"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Sal
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
# ganalytics: UA-113961478-1

# Authors
authors:
  pythonvishal:
    name: Vishal Chopra
    display_name: PythonVishal
    avatar: 'assets/images/sal.png'
    email: admin@pythonvishal.com
    web: https://www.pythonvishal.com
    twitter: https://twitter.com/pythonvishal
    description: "CA, CMA Finalist"

# Social
social:
  instagram: https://www.instagram.com/pythonvishal/
  facebook: https://www.facebook.com/pythonvishal
  twitter: https://twitter.com/pythonvishal

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
